Comment.create(:id => 1, :post_id => 3)
Comment.create(:id => 2, :post_id => 3)
Comment.create(:id => 3, :post_id => 3)
Comment.create(:id => 4, :post_id => 3)
Comment.create(:id => 5, :user_id => 1, :post_id => 5)
Comment.create(:id => 6, :user_id => 1, :post_id => 5)
Comment.create(:id => 7, :body => "asfdasd", :user_id => 1, :post_id => 5)
Comment.create(:id => 8, :body => "asdf", :user_id => 1, :post_id => 5)
Comment.create(:id => 9, :user_id => 1, :post_id => 5)
Comment.create(:id => 10, :body => "asd", :user_id => 1, :post_id => 5)
Comment.create(:id => 11, :user_id => 1, :post_id => 5)
Comment.create(:id => 12, :user_id => 1, :post_id => 5)
Comment.create(:id => 13, :body => "dsagfsdagsd", :user_id => 1, :post_id => 5)
Comment.create(:id => 14, :body => "as", :user_id => 1, :post_id => 5)
Comment.create(:id => 15, :body => "sdafsafd", :user_id => 1, :post_id => 5)
Comment.create(:id => 16, :user_id => 1, :post_id => 5)
Comment.create(:id => 17, :body => "dsafdsf", :user_id => 1, :post_id => 5)
Comment.create(:id => 18, :body => "dfasd", :user_id => 1, :post_id => 5)
Comment.create(:id => 19, :body => "dfasd", :user_id => 1, :post_id => 5)
Comment.create(:id => 20, :body => "dfasd", :user_id => 1, :post_id => 5)
Comment.create(:id => 21, :body => "dfasd", :user_id => 1, :post_id => 5)
Comment.create(:id => 22, :body => "dfasdfadsfsdafsad", :user_id => 1, :post_id => 5)
Comment.create(:id => 23, :body => "dfasdfadsfsdafsad", :user_id => 1, :post_id => 5)
Comment.create(:id => 24, :body => "dfasdfadsfsdafsad", :user_id => 1, :post_id => 5)
Comment.create(:id => 25, :body => "dfasdfadsfsdafsad", :user_id => 1, :post_id => 5)
Comment.create(:id => 26, :body => "dfasdfadsfsdafsad", :user_id => 1, :post_id => 5)
Comment.create(:id => 27, :body => "qqqqqqqqqqqqqqqqq", :user_id => 1, :post_id => 5)
Comment.create(:id => 28, :body => "qwe", :user_id => 1, :post_id => 5)
Comment.create(:id => 29, :body => "sadf", :user_id => 1, :post_id => 5)
Comment.create(:id => 30, :body => "adsfsda", :user_id => 1, :post_id => 5)
Comment.create(:id => 31, :body => "adf", :user_id => 1, :post_id => 5)
Comment.create(:id => 32, :body => "adf", :user_id => 1, :post_id => 5)
Comment.create(:id => 33, :body => "adf", :user_id => 1, :post_id => 5)
Comment.create(:id => 34, :body => "adf", :user_id => 1, :post_id => 5)
Comment.create(:id => 35, :body => "adf", :user_id => 1, :post_id => 5)
Comment.create(:id => 36, :body => "adf", :user_id => 1, :post_id => 5)
Comment.create(:id => 37, :body => "sdsadgsadgf", :user_id => 1, :post_id => 2)
Comment.create(:id => 38, :body => "q", :user_id => 1, :post_id => 2)
Comment.create(:id => 39, :body => "sadgf", :user_id => 1, :post_id => 2)
Comment.create(:id => 40, :body => "dSAF", :user_id => 1, :post_id => 2)
Comment.create(:id => 41, :body => "asdfsdaf", :user_id => 1, :post_id => 2)
Comment.create(:id => 42, :body => "asd", :user_id => 1, :post_id => 2)
Comment.create(:id => 43, :body => "sdf", :user_id => 1, :post_id => 2)
Comment.create(:id => 44, :body => "sdffsa", :user_id => 1, :post_id => 2)
Comment.create(:id => 45, :body => "1111", :user_id => 1, :post_id => 2)
Comment.create(:id => 46, :body => "aswd", :user_id => 1, :post_id => 2)
Comment.create(:id => 47, :body => "asdf", :user_id => 1, :post_id => 2)
Comment.create(:id => 48, :body => "qwe", :user_id => 1, :post_id => 2)
Comment.create(:id => 49, :body => "qwe", :user_id => 1, :post_id => 2)
Comment.create(:id => 50, :body => "asfd", :user_id => 1, :post_id => 2)
Comment.create(:id => 51, :body => "asdf", :user_id => 1, :post_id => 2)
Comment.create(:id => 52, :body => "1111", :user_id => 1, :post_id => 2)
Comment.create(:id => 53, :body => "1111", :user_id => 1, :post_id => 2)
Comment.create(:id => 54, :body => "dsafsdf", :user_id => 1, :post_id => 7)
Comment.create(:id => 55, :body => "dsafsdf", :user_id => 1, :post_id => 7)
Comment.create(:id => 56, :body => "qwe", :user_id => 1, :post_id => 9)
Comment.create(:id => 57, :body => "asd", :user_id => 1, :post_id => 9)
Comment.create(:id => 58, :body => "dsfsdaf", :user_id => 1, :post_id => 8)
Comment.create(:id => 59, :body => "dsfsdafqqqqq", :user_id => 1, :post_id => 8)
